apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  chart:
    spec:
      chart: ./local-charts/nginx
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  releaseName: nginx
